// Code generated by goctl. DO NOT EDIT.
package types

type SeedAddRequest struct {
	ScreenName string `json:"screenName"`
}

type SeedAddResponse struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}
