// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: seed.proto

package seed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeedAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScreenName string `protobuf:"bytes,1,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
}

func (x *SeedAddRequest) Reset() {
	*x = SeedAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedAddRequest) ProtoMessage() {}

func (x *SeedAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedAddRequest.ProtoReflect.Descriptor instead.
func (*SeedAddRequest) Descriptor() ([]byte, []int) {
	return file_seed_proto_rawDescGZIP(), []int{0}
}

func (x *SeedAddRequest) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

type SeedAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SeedAddResponse) Reset() {
	*x = SeedAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedAddResponse) ProtoMessage() {}

func (x *SeedAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedAddResponse.ProtoReflect.Descriptor instead.
func (*SeedAddResponse) Descriptor() ([]byte, []int) {
	return file_seed_proto_rawDescGZIP(), []int{1}
}

func (x *SeedAddResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SeedAddResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_seed_proto protoreflect.FileDescriptor

var file_seed_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x65,
	0x65, 0x64, 0x22, 0x31, 0x0a, 0x0e, 0x53, 0x65, 0x65, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x53, 0x65, 0x65, 0x64, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x45,
	0x0a, 0x0b, 0x53, 0x65, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x53, 0x65, 0x65, 0x64, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x65, 0x64, 0x2e,
	0x53, 0x65, 0x65, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x73, 0x65, 0x65, 0x64, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x73, 0x65, 0x65, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seed_proto_rawDescOnce sync.Once
	file_seed_proto_rawDescData = file_seed_proto_rawDesc
)

func file_seed_proto_rawDescGZIP() []byte {
	file_seed_proto_rawDescOnce.Do(func() {
		file_seed_proto_rawDescData = protoimpl.X.CompressGZIP(file_seed_proto_rawDescData)
	})
	return file_seed_proto_rawDescData
}

var file_seed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_seed_proto_goTypes = []interface{}{
	(*SeedAddRequest)(nil),  // 0: seed.SeedAddRequest
	(*SeedAddResponse)(nil), // 1: seed.SeedAddResponse
}
var file_seed_proto_depIdxs = []int32{
	0, // 0: seed.SeedService.AddSeed:input_type -> seed.SeedAddRequest
	1, // 1: seed.SeedService.AddSeed:output_type -> seed.SeedAddResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seed_proto_init() }
func file_seed_proto_init() {
	if File_seed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeedAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeedAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seed_proto_goTypes,
		DependencyIndexes: file_seed_proto_depIdxs,
		MessageInfos:      file_seed_proto_msgTypes,
	}.Build()
	File_seed_proto = out.File
	file_seed_proto_rawDesc = nil
	file_seed_proto_goTypes = nil
	file_seed_proto_depIdxs = nil
}
