// Code generated by goctl. DO NOT EDIT.
// Source: seed.proto

package server

import (
	"context"

	"bluebird/rpc/seed/internal/logic"
	"bluebird/rpc/seed/internal/svc"
	"bluebird/rpc/seed/seed"
)

type SeedServiceServer struct {
	svcCtx *svc.ServiceContext
	seed.UnimplementedSeedServiceServer
}

func NewSeedServiceServer(svcCtx *svc.ServiceContext) *SeedServiceServer {
	return &SeedServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SeedServiceServer) AddSeed(ctx context.Context, in *seed.SeedAddRequest) (*seed.SeedAddResponse, error) {
	l := logic.NewAddSeedLogic(ctx, s.svcCtx)
	return l.AddSeed(in)
}
